version: '3.8'

services:
  # Service principal de l'application Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: relational-partner-manager-frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # Monter le code source en mode développement (optionnel)
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - app-network

  # Service pour le développement avec hot reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: relational-partner-manager-dev
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: pnpm run dev
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - dev

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  next_cache:
