#!/bin/bash

echo "📝 Guide des messages de commit"
echo "==============================="
echo ""
echo "Format OBLIGATOIRE : [gitmoji] type(scope): description"
echo ""
echo "LES TROIS ÉLÉMENTS SONT OBLIGATOIRES :"
echo "1. 🎭 Gitmoji (code :emoji: OU émoji 🎭)"
echo "2. 🏷️  Type conventionnel"
echo "3. 💬 Message descriptif (minimum 5 caractères)"
echo ""
echo "📚 TYPES AUTORISÉS :"
echo "  feat      :sparkles: ✨ Nouvelle fonctionnalité"
echo "  fix       :bug: 🐛 Correction de bug"
echo "  docs      :memo: 📝 Documentation"
echo "  style     :art: 🎨 Style de code (formatting, etc.)"
echo "  refactor  :recycle: ♻️  Refactoring"
echo "  perf      :zap: ⚡ Amélioration des performances"
echo "  test      :white_check_mark: ✅ Tests"
echo "  chore     :wrench: 🔧 Maintenance/tâches diverses"
echo "  ci        :green_heart: 💚 Intégration continue"
echo "  build     :package: 📦 Build/dépendances"
echo "  revert    :rewind: ⏪ Annulation de commit"
echo "  security  :lock: 🔒 Sécurité"
echo "  config    :gear: ⚙️  Configuration"
echo ""
echo "🎯 SCOPES SUGGÉRÉS :"
echo "  auth, partners, users, classifications, notifications,"
echo "  stats, api, ui, config, database, security, tests, docs"
echo ""
echo "✅ EXEMPLES VALIDES :"
echo "  :sparkles: feat(auth): add OAuth2 LinkedIn integration"
echo "  ✨ feat(auth): add OAuth2 LinkedIn integration"
echo "  :bug: fix(partners): resolve pagination bug"
echo "  � fix(partners): resolve pagination bug"
echo "  :memo: docs(readme): update installation guide"
echo "  📝 docs(readme): update installation guide"
echo "  :wrench: chore: improve commit configuration"
echo "  � chore: improve commit configuration"
echo ""
echo "❌ EXEMPLES INVALIDES :"
echo "  'update readme'                    → Pas de gitmoji ni type"
echo "  'feat: add login'                  → Pas de gitmoji"
echo "  '✨ add login'                     → Pas de type"
echo "  '✨ feat: fix'                     → Message trop court"
echo "  '✨ invalid: add login'            → Type invalide"
echo ""
echo "🔗 LIENS UTILES :"
echo "  Gitmojis: https://gitmoji.dev/"
echo "  Conventional Commits: https://conventionalcommits.org/"
echo ""
echo "🧪 Pour tester votre message :"
echo "  echo 'votre message' | pnpx commitlint"
echo ""
echo "💡 Utiliser gitmoji-cli pour commits interactifs :"
echo "  pnpm run commit"
